### PR TITLE
fix: Compilation with esp-idf 5.5

### LINKED ISSUE #150: Does not compile with ESP-IDF v5.5 (AEGHB-1186)
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

Compile when building with ESP-IDF 5.5

### Actual behavior (suspected bug)

Fails to compile.

1. missing `REQUIRES` for `esp_driver_gpio`, `esp_driver_uart`, and `esp_driver_usb_serial_jtag`
2. Has incompatible function pointer type:

```console
/Users/bob/finger563/esp-now/src/espnow/src/espnow.c:1086:46: error: passing argument 1 of 'esp_now_register_send_cb' from incompatible pointer type [-Wincompatible-pointer-types]
 1086 |     ESP_ERROR_CHECK(esp_now_register_send_cb(espnow_send_cb));
      |                                              ^~~~~~~~~~~~~~
      |                                              |
      |                                              void (*)(const uint8_t *, esp_now_send_status_t) {aka void (*)(const unsigned char *, esp_now_send_status_t)}
/Users/bob/esp/esp-idf/components/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
In file included from /Users/bob/finger563/esp-now/src/espnow/src/espnow.c:18:
/Users/bob/esp/esp-idf/components/esp_wifi/include/esp_now.h:185:54: note: expected 'esp_now_send_cb_t' {aka 'void (*)(const wifi_tx_info_t *, esp_now_send_status_t)'} but argument is of type 'void (*)(const uint8_t *, esp_now_send_status_t)' {aka 'void (*)(const unsigned char *, esp_now_send_status_t)'}
  185 | esp_err_t esp_now_register_send_cb(esp_now_send_cb_t cb);
      |                                    ~~~~~~~~~~~~~~~~~~^~
```

### Error logs or terminal output

```shell
/Users/bob/finger563/esp-now/src/espnow/src/espnow.c:1086:46: error: passing argument 1 of 'esp_now_register_send_cb' from incompatible pointer type [-Wincompatible-pointer-types]
 1086 |     ESP_ERROR_CHECK(esp_now_register_send_cb(espnow_send_cb));
      |                                              ^~~~~~~~~~~~~~
      |                                              |
      |                                              void (*)(const uint8_t *, esp_now_send_status_t) {aka void (*)(const unsigned char *, esp_now_send_status_t)}
/Users/bob/esp/esp-idf/components/esp_common/include/esp_err.h:116:30: note: in definition of macro 'ESP_ERROR_CHECK'
  116 |         esp_err_t err_rc_ = (x);                                        \
      |                              ^
In file included from /Users/bob/finger563/esp-now/src/espnow/src/espnow.c:18:
/Users/bob/esp/esp-idf/components/esp_wifi/include/esp_now.h:185:54: note: expected 'esp_now_send_cb_t' {aka 'void (*)(const wifi_tx_info_t *, esp_now_send_status_t)'} but argument is of type 'void (*)(const uint8_t *, esp_now_send_status_t)' {aka 'void (*)(const unsigned char *, esp_now_send_status_t)'}
  185 | esp_err_t esp_now_register_send_cb(esp_now_send_cb_t cb);
      |                                    ~~~~~~~~~~~~~~~~~~^~
```

### Steps to reproduce the behavior

1. Use ESP-IDF 5.5
2. try to build one of the examples (in this case the `switch` example)

### Project release version

`master` branch

### System architecture

ARM 64-bit (Apple M1/M2, Raspberry Pi 4/5)

### Operating system

MacOS

### Operating system version

MacOS

### Shell

ZSH

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by finger563**
## Description

Fixes compilation of esp-now with ESP-IDF v5.5

## Related

Closes #150 

## Testing

Build the examples.

---

## Checklist

Before submitting a Pull Request, please ensure the following:

- [x] 🚨 This PR does not introduce breaking changes.
- [x] All CI checks (GH Actions) pass.
- [x] Documentation is updated as needed.
- [x] Tests are updated or added as necessary.
- [x] Code is well-commented, especially in complex areas.
- [x] Git history is clean — commits are squashed to the minimum necessary.

### CODE REVIEW

**Comment by DCSBL** [comment]
Hi @lhespress, sorry for pinging you. It looks like you are (one of) the maintainers.

We actually need this PR to bump our firmware to ESP-IDF v5.5. Can you take a minute to accept this PR?

**Comment by finger563** [comment]
> Hi @lhespress, sorry for pinging you. It looks like you are (one of) the maintainers.
> 
> We actually need this PR to bump our firmware to ESP-IDF v5.5. Can you take a minute to accept this PR?

@DCSBL if you need to use this component with the fix and you're using the idf component manager, then you can use the version published under the esp-cpp namespace. It's what I'm using and it's hosted at espp/esp-now on the main branch of this fork

https://components.espressif.com/components/espp/esp-now/versions/1.0.5/readme
